CREATE TABLE IF NOT EXISTS `org` (
  `id` SERIAL NOT NULL COMMENT 'unique user id',
  `name` VARCHAR(256) NOT NULL COMMENT 'friendly company name',

  `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `last_update` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`)
)

ENGINE = InnoDB
DEFAULT CHARSET = utf8;