CREATE TABLE IF NOT EXISTS `unit_ext` (
  `unit_id` BIGINT UNSIGNED NOT NULL,
  `ext` JSON NOT NULL COMMENT 'custom user defined attributes',

  `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `last_update` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

   FOREIGN KEY (unit_id) REFERENCES unit(id)
     ON UPDATE CASCADE ON DELETE CASCADE
)

ENGINE = InnoDB
DEFAULT CHARSET = utf8;